### ISSUE TITLE
Interpreter selection ignored in pynotepad. If corrected, 'PyCodeEdit' object is not callable

### ISSUE THREAD

**Issue by jfdupuis** [pyQode/pyQode#25]
in pyqode.python/examples/pynotepad/pynotepad/main_window.py

line 25:
self.tabWidget.register_code_edit(PyCodeEdit)

should be:
PyCodeEdit(None, server.__file__, Settings().interpreter)

Otherwise the interpreter set in Settings is ignored.

When embedding pynotepad in a c++ application, the sys.executable is not python and the problem is triggered. While this solve the interpreter selection problem, I then get:

Traceback (most recent call last):
  File "SOME_PATH/pynotepad/pynotepad/main_window.py", line 137, in on_open
    self.open_file(filename)
  File "SOME_PATH/pynotepad/pynotepad/main_window.py", line 110, in open_file
    editor = self.tabWidget.open_document(path)
  File "/usr/local/lib/python3.4/site-packages/pyqode.core-2.4.2-py3.4.egg/pyqode/core/api/utils.py", line 1088, in wrapper
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pyqode.core-2.4.2-py3.4.egg/pyqode/core/widgets/splittable_tab_widget.py", line 878, in open_document
    *args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pyqode.core-2.4.2-py3.4.egg/pyqode/core/widgets/splittable_tab_widget.py", line 821, in _create_code_edit
    *args, parent=self.main_tab_widget, **kwargs)
TypeError: 'PyCodeEdit' object is not callable

**Comment by jfdupuis** [comment]
To reproduce the not callable problem, one can simply change
pyqode.python/examples/pynotepad/pynotepad/main_window.py:25 to

self.tabWidget.register_code_edit(PyCodeEdit())

**Comment by ColinDuquesnoy** [comment]
Thank you for the report. Looks like I forgot to pass the intepreter settings when creating a new document (or opening an existing one) when I integrated the new splittable tab widget.

``tabWidget.register_code_edit`` expects a class, not an instance. The constructor parameters need to be passed to ``tabWidget.open_document`` and ``tabWidget.create_new_document`` (https://github.com/pyQode/pyqode.python/blob/master/examples/pynotepad/pynotepad/main_window.py#L124)

This is fixed in master branch.
